name: blog-app-ci # version: (obsolete)

services:
  blog-db:
    image: "mysql"
    restart: unless-stopped

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - blog-db-vol:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - blog-net

  blog-server:
    image: "mibitstech/blog-app:v3"
    restart: unless-stopped
    depends_on:
      - blog-db
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:3000/health",
        ]
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - "3001:3000"
    environment:
      - DB_HOST=blog-db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=blogdb
      - MYSQL_ROOT_PASSWORD=root
      - NODE_HOST="{{.Node.Hostname}}"

    networks:
      - blog-net

volumes:
  blog-db-vol:

networks:
  blog-net:
